CREATE TABLE players (
    id UUID PRIMARY KEY DEFAULT UUID(),
    discord_id BIGINT UNSIGNED UNIQUE NOT NULL,
    username VARCHAR(16) UNIQUE NOT NULL,
    wins INT UNSIGNED DEFAULT 0,
    total_games INT UNSIGNED DEFAULT 0,
    highest_win_streak INT UNSIGNED DEFAULT 0,
    win_streak INT UNSIGNED DEFAULT 0,
    highest_rating INT UNSIGNED DEFAULT 0,
    rating INT UNSIGNED DEFAULT 1500,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
