CREATE TABLE IF NOT EXISTS players (
    id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    rating INT UNSIGNED DEFAULT 0,
    wins INT UNSIGNED DEFAULT 0,
    losses INT UNSIGNED DEFAULT 0,
    registered_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
